-- R&D "Roles & Hiring" section: what a setter/processor/closer is, what they
-- do, comp norms (industry-estimate where researched), where to hire them
-- (verified links), and the plan rules that bind each role. Seeded once,
-- idempotently, into the existing rnd_items table.

do $$
begin
  if not exists (select 1 from public.rnd_items where section='roles') then
    insert into public.rnd_items (section, kind, label, content, sort_order) values

    ('roles','note','Setter',
     '{"role":"Setter","aka":"opener / appointment setter","definition":"Dials the UCC and aged lists all day (the plan''s 200 dials/day), qualifies on the BANT-F basics, and drives every good call to a COMPLETE FILE. Not a seller — a qualifier and collector.","responsibilities":["Run ~200 dials/day against the UCC / aged lists","Qualify on BANT-F: monthly revenue, time in business, amount wanted, existing positions","Ask for the payoff letter on the call","Drive to a complete file — e-signed app + bank statements, collected on the call or via the upload link"],"comp":"Offshore $4–8/hr base + a per-verified-complete-file bonus of $25–50.","compLabel":"industry estimate","compRule":"Pay on verified complete files — never on appointments.","sources":[{"label":"OnlineJobs.ph","url":"https://www.onlinejobs.ph/"},{"label":"The Calling Agency","url":"https://callingagency.com/"},{"label":"Somewhere.com (LatAm / PH)","url":"https://somewhere.com/"},{"label":"Upwork","url":"https://www.upwork.com/"},{"label":"Techmart","unverified":true}],"rule":"Setter never touches bank credentials.","ruleRef":"Rules That Keep It Alive"}',1),

    ('roles','note','Processor',
     '{"role":"Processor","aka":"file processor / deal scrubber","definition":"The quality gate between setters and funders. QCs every file for fraud, packages to each funder''s format, submits, chases stips, and tracks offers.","responsibilities":["QC every file for fraud — one doctored statement can end a funder relationship","Package each deal to the funder''s required format","Submit in funder order and chase approval stips","Track offers back from underwriting"],"comp":"Per-deal contractors $50–150/file (DailyFunder scrubbers), or an offshore salaried processor $800–1,500/mo once volume justifies it.","compLabel":"industry estimate","builtBadge":"partially built","builtDetail":"Our platform already automates much of this — submission recipes, package preview, and document classification — so a processor manages exceptions rather than every keystroke.","sources":[{"label":"DailyFunder forum","url":"https://dailyfunder.com/forumdisplay.php/2-Merchant-Cash-Advance"},{"label":"LinkedIn MCA groups","url":"https://www.linkedin.com/search/results/groups/?keywords=merchant%20cash%20advance"},{"label":"Funder ISO-rep referrals","appLink":"/admin/funder-directory","appLinkLabel":"Funder Directory"}],"rule":"Processor QCs every file — one doctored statement can end a funder relationship.","ruleRef":"Rules That Keep It Alive"}',2),

    ('roles','note','Closer',
     '{"role":"Closer","definition":"Takes the qualified, complete file, presents 2+ offers side by side, handles objections, gets contracts signed, and owns the merchant relationship through funding and renewals.","responsibilities":["Present 2+ offers side-by-side","Handle objections and get the contracts signed","Own the merchant relationship through funding","Work the renewal ladder at 50–60% paydown"],"comp":"1099 commission splits — 35% on company leads / 65% self-generated / 30% on renewals, per our Independent Contractor Commission Agreement. Splits are set per closer.","compLabel":"our structure","builtBadge":"already built","builtDetail":"The comp structure and per-closer split settings already live in Admin → Closers. Carlos is the current closer.","sources":[{"label":"DailyFunder job board","url":"https://dailyfunder.com/"},{"label":"LinkedIn (MCA / business funding)","url":"https://www.linkedin.com/search/results/groups/?keywords=merchant%20cash%20advance"},{"label":"Indeed — \"MCA closer\"","url":"https://www.indeed.com/jobs?q=MCA+closer"},{"label":"Closers (Admin)","appLink":"/admin/closers","appLinkLabel":"Admin → Closers"}],"rule":"The closer gets hired at Phase 3 — when there''s flow to feed them, not before.","ruleRef":"Rules That Keep It Alive"}',3);
  end if;
end$$;
