-- ph_ucc_19: Big funder-roster merge — add 470 verified MCA/RBF filing identities.
-- =============================================================================
-- Source: MFunding canonical funder roster (402 funders / 724 filing identities,
-- compiled from deBanked UCC alias registry, FunderIntel, Grant Phillips Law,
-- NY AG Yellowstone settlement, FTC RCG, KBRA securitization reports) merged with
-- the empirical top-unmatched secured-party aggregation across CT/CO/OR/FL/CA.
--
-- Every alias below was PRECISION-TESTED with zero DB egress against the full
-- local secured-party universe (21,554 distinct raw names across the 5 states),
-- mirroring ph_ucc_norm / ph_ucc_norm_full / ph_ucc_is_depository EXACTLY:
--   * token mode ONLY where the funder's distinctive core matches its own name +
--     its own shells and NO foreign company (verified per-candidate).
--   * exact mode where the name collapses to a generic token under ph_ucc_norm
--     (which strips FUNDING/CAPITAL/GROUP/…) — full-name equality on
--     ph_ucc_norm_full so it matches ONLY that funder.
-- HARD-EXCLUDED (never added): filing agents (CSC/CT Corp/Wolters Kluwer/First
-- Corporate Solutions/Financial Agent Services/Secured Lender Solutions/NRAI),
-- partner banks behind fintechs (WebBank/Celtic/Cross River/First Electronic/…),
-- card processors (First Data / Fiserv), and depository names (bank guard).
-- 86 aliases recover real filings now; the rest are precise future-proofs.
-- 40 are funder SHELLS/SPVs that roll up under the parent (canonical_name).
-- =============================================================================

-- ── TOKEN-mode aliases (369) ──────────────────────────────────────────
insert into public.ph_ucc_funder_aliases (alias, canonical_name, source, active, match_mode) values
  ('EBF Holdings, LLC', 'Everest Business Funding', 'debanked', true, 'token'),
  ('Bitty Advance 2, LLC', 'Bitty Advance', 'debanked', true, 'token'),
  ('The LCF Group, Inc. (f/k/a Last Chance Funding, Inc.)', 'The LCF Group', 'debanked', true, 'token'),
  ('Samson Funding', 'Samson Funding', 'debanked', true, 'token'),
  ('Samson MCA', 'Samson Funding', 'debanked', true, 'token'),
  ('Samson MCA LLC', 'Samson Funding', 'debanked', true, 'token'),
  ('Samson Group', 'Samson Funding', 'debanked', true, 'token'),
  ('Alpine Advance', 'Alpine Advance', 'debanked', true, 'token'),
  ('Alpine Advance 5 LLC', 'Alpine Advance', 'debanked', true, 'token'),
  ('Square Financial Services, Inc.', 'Square Capital', 'debanked', true, 'token'),
  ('Parafin', 'Parafin', 'debanked', true, 'token'),
  ('Parafin, Inc.', 'Parafin', 'debanked', true, 'token'),
  ('Merchant Cash and Capital', 'Merchant Cash and Capital', 'debanked', true, 'token'),
  ('Merchant Advance Pay', 'Merchant Advance Pay', 'debanked', true, 'token'),
  ('Epic Advance', 'Epic Advance', 'debanked', true, 'token'),
  ('Epic Advance, Inc', 'Epic Advance', 'debanked', true, 'token'),
  ('BizFunds', 'BizFunds', 'debanked', true, 'token'),
  ('Spartan Capital', 'Spartan Capital', 'debanked', true, 'token'),
  ('Spartan Capital Group LLC', 'Spartan Capital', 'debanked', true, 'token'),
  ('Legend Advance Funding', 'Legend Advance Funding', 'debanked', true, 'token'),
  ('Legend Advance Funding LLC', 'Legend Advance Funding', 'debanked', true, 'token'),
  ('Channel Partners Capital', 'Channel Partners Capital', 'debanked', true, 'token'),
  ('Channel Partners Capital, LLC', 'Channel Partners Capital', 'debanked', true, 'token'),
  ('Ironwood Finance', 'Ironwood Finance', 'debanked', true, 'token'),
  ('Avanza Capital', 'Avanza Capital', 'debanked', true, 'token'),
  ('Blackbridge Investment Group', 'BIG (Blackbridge Investment Group)', 'debanked', true, 'token'),
  ('Bridgecap Financial', 'Bridgecap Financial', 'debanked', true, 'token'),
  ('Bridgecap Financial LLC', 'Bridgecap Financial', 'debanked', true, 'token'),
  ('Coolidge Capital', 'Coolidge Capital', 'debanked', true, 'token'),
  ('Equita Advance', 'Equita Advance', 'debanked', true, 'token'),
  ('Flagler Advance', 'Flagler Advance', 'debanked', true, 'token'),
  ('ForwardLine Financial', 'Forward Line', 'debanked', true, 'token'),
  ('Fratello Capital', 'Fratello Capital', 'debanked', true, 'token'),
  ('G and G Funding', 'G and G Funding', 'debanked', true, 'token'),
  ('Lending Valley', 'Lending Valley', 'debanked', true, 'token'),
  ('Lendora', 'Lendora', 'debanked', true, 'token'),
  ('Lendr', 'Lendr', 'debanked', true, 'token'),
  ('Lendspark', 'Lendspark', 'debanked', true, 'token'),
  ('Lendspark Corporation', 'Lendspark', 'debanked', true, 'token'),
  ('Lifetime Funding', 'Lifetime Funding', 'debanked', true, 'token'),
  ('Olympus Lending', 'Olympus Lending', 'debanked', true, 'token'),
  ('Overnight Capital', 'Overnight Capital', 'debanked', true, 'token'),
  ('Overnight Capital LLC', 'Overnight Capital', 'debanked', true, 'token'),
  ('Paz Funding Source', 'Paz Funding Source', 'debanked', true, 'token'),
  ('Rowan Advance', 'Rowan Advance', 'debanked', true, 'token'),
  ('SG Credit Partners', 'SG Credit Partners', 'debanked', true, 'token'),
  ('SG Credit Partners, Inc.', 'SG Credit Partners', 'debanked', true, 'token'),
  ('Silverline Capital Group', 'Silverline Capital Group', 'debanked', true, 'token'),
  ('Silverline', 'Silverline Capital Group', 'debanked', true, 'token'),
  ('Spier Capital', 'Spier Capital', 'debanked', true, 'token'),
  ('Thoro Corp', 'Thoro Corp', 'debanked', true, 'token'),
  ('Trustify Advance', 'Trustify Advance', 'debanked', true, 'token'),
  ('Unique Funding Solutions', 'Unique Funding Solutions', 'debanked', true, 'token'),
  ('Wall Street Funding', 'Wall Street Funding', 'debanked', true, 'token'),
  ('Wellen Capital', 'Wellen Capital', 'debanked', true, 'token'),
  ('Wellen', 'Wellen Capital', 'debanked', true, 'token'),
  ('Windgate Capital', 'Windgate Capital', 'debanked', true, 'token'),
  ('Monday Funding', 'Monday Funding', 'debanked', true, 'token'),
  ('Total Merchant Resources', 'Total Merchant Resources', 'debanked', true, 'token'),
  ('Total Merchant Resources, LLC', 'Total Merchant Resources', 'debanked', true, 'token'),
  ('1st Alliance Group', '1st Alliance Group', 'debanked', true, 'token'),
  ('1st Alliance Group LLC', '1st Alliance Group', 'debanked', true, 'token'),
  ('Biz Capital Miami', 'Biz Capital Miami', 'debanked', true, 'token'),
  ('Panthers Capital', 'Panthers Capital', 'debanked', true, 'token'),
  ('Alpha Capital Source', 'Alpha Capital Source', 'debanked', true, 'token'),
  ('Atipana Capital', 'Atipana Capital', 'debanked', true, 'token'),
  ('Atipana Capital LLC', 'Atipana Capital', 'debanked', true, 'token'),
  ('Uncapped', 'Uncapped', 'debanked', true, 'token'),
  ('Pipe Technologies, Inc.', 'Pipe', 'debanked', true, 'token'),
  ('Fundry', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Fundry LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Delta Bridge Funding LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('ABC Merchant Solutions LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Advance Merchant Services LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Business Advance Team LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Cash Village Funding LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Fundzio LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('HFH Merchant Services LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('High Speed Capital LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Merchant Capital Pay LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Midnight Advance Capital LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Mr. Advance Capital LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Ocean 1213 LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Simply Equities LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('TVT Cap Fund LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('TVT Capital HR LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Thryve Capital Funding LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('West Coast Business Capital LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('Yellowstone Capital West', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('World Global Capital LLC', 'Yellowstone Capital', 'debanked', true, 'token'),
  ('RCG Advances', 'Richmond Capital Group', 'debanked', true, 'token'),
  ('RCG Advances, LLC (f/k/a Richmond Capital Group, LLC)', 'Richmond Capital Group', 'debanked', true, 'token'),
  ('RetailCapital', 'Credibly', 'debanked', true, 'token'),
  ('Credibly Asset Securitization LLC', 'Credibly', 'debanked', true, 'token'),
  ('Kapitus Asset Securitization LLC', 'Kapitus', 'debanked', true, 'token'),
  ('RapidAdvance', 'RapidAdvance', 'debanked', true, 'token'),
  ('Rapid Financial Services, LLC', 'RapidAdvance', 'debanked', true, 'token'),
  ('Small Business Financial Solutions, LLC', 'RapidAdvance', 'debanked', true, 'token'),
  ('Pearl Capital Business Funding, LLC', 'Pearl Capital', 'debanked', true, 'token'),
  ('Pearl Capital Rivis Ventures, LLC', 'Pearl Capital', 'debanked', true, 'token'),
  ('Pearl Alpha Funding', 'Pearl Capital', 'debanked', true, 'token'),
  ('Pearl Gamma Funding', 'Pearl Capital', 'debanked', true, 'token'),
  ('Full Spectrum Processing, Inc.', 'Par Funding', 'debanked', true, 'token'),
  ('EBF Partners, LLC', 'Everest Business Funding', 'debanked', true, 'token'),
  ('Fox Business Funding', 'Fox Business Funding', 'debanked', true, 'token'),
  ('OnDeck (Enova)', 'OnDeck (Enova)', 'debanked', true, 'token'),
  ('OnDeck Asset Securitization Trust II LLC (ODAST II)', 'OnDeck (Enova)', 'debanked', true, 'token'),
  ('OnDeck Asset Securitization Trust (ODAST)', 'OnDeck (Enova)', 'debanked', true, 'token'),
  ('KCG Securitization, LLC', 'Kalamata Capital Group', 'debanked', true, 'token'),
  ('KCG Securitization II, LLC', 'Kalamata Capital Group', 'debanked', true, 'token'),
  ('Snap Advances', 'Snap Advances', 'debanked', true, 'token'),
  ('Nextwave Enterprises', 'Nextwave Enterprises', 'debanked', true, 'token'),
  ('Nextwave Enterprises, LLC', 'Nextwave Enterprises', 'debanked', true, 'token'),
  ('Capital For Merchants', 'Capital For Merchants', 'debanked', true, 'token'),
  ('Capital For Merchants LLC', 'Capital For Merchants', 'debanked', true, 'token'),
  ('AmeriMerchant', 'AmeriMerchant', 'debanked', true, 'token'),
  ('Capify', 'AmeriMerchant', 'debanked', true, 'token'),
  ('Principis Capital', 'Principis Capital', 'debanked', true, 'token'),
  ('Smart Step Funding', 'Principis Capital', 'debanked', true, 'token'),
  ('Principis Capital LLC', 'Principis Capital', 'debanked', true, 'token'),
  ('Business Financial Services (BFS Capital)', 'Business Financial Services (BFS Capital)', 'debanked', true, 'token'),
  ('Boca Capital Partners', 'Boca Capital Partners', 'debanked', true, 'token'),
  ('Yalber', 'Yalber', 'debanked', true, 'token'),
  ('Romi Merchant Services', 'Romi Merchant Services', 'debanked', true, 'token'),
  ('Strategic Funding Partners', 'Merchant Cash Group', 'debanked', true, 'token'),
  ('Merchants Capital Access', 'Merchants Capital Access', 'debanked', true, 'token'),
  ('IRN Payment Systems', 'IRN Payment Systems', 'debanked', true, 'token'),
  ('Direct Merchant Funding', 'Direct Merchant Funding', 'debanked', true, 'token'),
  ('Direct Merchant Funding LLC', 'Direct Merchant Funding', 'debanked', true, 'token'),
  ('DF Merchant Advance', 'DF Merchant Advance', 'debanked', true, 'token'),
  ('American Merchant Receivables', 'American Merchant Receivables', 'debanked', true, 'token'),
  ('American Merchant Receivables LLC', 'American Merchant Receivables', 'debanked', true, 'token'),
  ('American Stimulus Funding', 'American Stimulus Funding', 'debanked', true, 'token'),
  ('Finish Line Capital', 'Finish Line Capital', 'debanked', true, 'token'),
  ('Knight Capital Funding II, LLC', 'Knight Capital Funding', 'debanked', true, 'token'),
  ('Premium Merchant Funding One, LLC', 'Premium Merchant Funding', 'debanked', true, 'token'),
  ('Business Credit and Capital', 'Business Credit and Capital', 'debanked', true, 'token'),
  ('Lending Club', 'Lending Club', 'debanked', true, 'token'),
  ('LendingClub Corporation', 'Lending Club', 'debanked', true, 'token'),
  ('Yellowstone-linked TVT Capital', 'Yellowstone-linked TVT Capital', 'debanked', true, 'token'),
  ('GoKapital', 'GoKapital', 'debanked', true, 'token'),
  ('GoKapital, Inc.', 'GoKapital', 'debanked', true, 'token'),
  ('Sunwise Capital', 'Sunwise Capital', 'debanked', true, 'token'),
  ('Sunwise Capital, LLC', 'Sunwise Capital', 'debanked', true, 'token'),
  ('Prosperum Capital', 'Prosperum Capital', 'debanked', true, 'token'),
  ('Prosperum Capital Partners LLC', 'Prosperum Capital', 'debanked', true, 'token'),
  ('Prosperum Funding LLC', 'Prosperum Capital', 'debanked', true, 'token'),
  ('Capybara Capital', 'Capybara Capital', 'debanked', true, 'token'),
  ('Capybara Capital LLC', 'Capybara Capital', 'debanked', true, 'token'),
  ('Newco Capital Group', 'Newco Capital Group', 'debanked', true, 'token'),
  ('Newco Capital Group VI LLC', 'Newco Capital Group', 'debanked', true, 'token'),
  ('AJ Equity Group', 'AJ Equity Group', 'debanked', true, 'token'),
  ('AJ Equity Group LLC', 'AJ Equity Group', 'debanked', true, 'token'),
  ('A&J Equity', 'AJ Equity Group', 'debanked', true, 'token'),
  ('Itria Ventures (Biz2Credit)', 'Itria Ventures (Biz2Credit)', 'debanked', true, 'token'),
  ('Biz2Credit', 'Itria Ventures (Biz2Credit)', 'debanked', true, 'token'),
  ('Biz2Capital', 'Itria Ventures (Biz2Credit)', 'debanked', true, 'token'),
  ('PowerUp Lending Group', 'PowerUp Lending Group', 'debanked', true, 'token'),
  ('Power Up Lending Group, Ltd.', 'PowerUp Lending Group', 'debanked', true, 'token'),
  ('CFGMS', 'CFG Merchant Solutions', 'debanked', true, 'token'),
  ('Revenued', 'Revenued', 'debanked', true, 'token'),
  ('Revenued (NEWCO Capital-affiliated)', 'Revenued', 'debanked', true, 'token'),
  ('Kabbage, Inc. (now American Express / Amex Kabbage)', 'Kabbage', 'debanked', true, 'token'),
  ('PayPal Working Capital', 'PayPal Working Capital', 'debanked', true, 'token'),
  ('PayPal (product)', 'PayPal Working Capital', 'debanked', true, 'token'),
  ('PayPal Business Loan', 'PayPal Working Capital', 'debanked', true, 'token'),
  ('LoanBuilder', 'PayPal Working Capital', 'debanked', true, 'token'),
  ('Square Loans', 'Square Capital', 'debanked', true, 'token'),
  ('Stripe Capital', 'Stripe Capital', 'debanked', true, 'token'),
  ('Stripe (product)', 'Stripe Capital', 'debanked', true, 'token'),
  ('Shopify Capital', 'Shopify Capital', 'debanked', true, 'token'),
  ('Shopify Capital Inc.', 'Shopify Capital', 'debanked', true, 'token'),
  ('Shopify Lending', 'Shopify Capital', 'debanked', true, 'token'),
  ('Toast Capital', 'Toast Capital', 'debanked', true, 'token'),
  ('Toast, Inc. (product)', 'Toast Capital', 'debanked', true, 'token'),
  ('Amazon Capital Services', 'Amazon Capital Services', 'debanked', true, 'token'),
  ('Amazon Lending', 'Amazon Capital Services', 'debanked', true, 'token'),
  ('Amazon Capital Services, Inc.', 'Amazon Capital Services', 'debanked', true, 'token'),
  ('BlueVine', 'BlueVine', 'debanked', true, 'token'),
  ('Bluevine Capital Inc.', 'BlueVine', 'debanked', true, 'token'),
  ('Fundbox', 'Fundbox', 'debanked', true, 'token'),
  ('Fundbox, Inc.', 'Fundbox', 'debanked', true, 'token'),
  ('Parafin Cash Advance', 'Parafin', 'debanked', true, 'token'),
  ('Wayflyer', 'Wayflyer', 'debanked', true, 'token'),
  ('Wayflyer Inc.', 'Wayflyer', 'debanked', true, 'token'),
  ('Clearco (Clearbanc)', 'Clearco (Clearbanc)', 'debanked', true, 'token'),
  ('Clearbanc', 'Clearco (Clearbanc)', 'debanked', true, 'token'),
  ('The Business Backer', 'The Business Backer', 'debanked', true, 'token'),
  ('The Business Backer, LLC', 'The Business Backer', 'debanked', true, 'token'),
  ('Quick Cash Business Services', 'Quick Cash Business Services', 'debanked', true, 'token'),
  ('Professional Merchant Advance Capital', 'Professional Merchant Advance Capital', 'debanked', true, 'token'),
  ('New Era Lending', 'New Era Lending', 'debanked', true, 'token'),
  ('New Era Lending LLC', 'New Era Lending', 'debanked', true, 'token'),
  ('Money for Merchants', 'Money for Merchants', 'debanked', true, 'token'),
  ('Merchant Resources International', 'Merchant Resources International', 'debanked', true, 'token'),
  ('Merchant Cash Advance of Texas', 'Merchant Cash Advance of Texas', 'debanked', true, 'token'),
  ('Merchant Capital Source', 'Merchant Capital Source', 'debanked', true, 'token'),
  ('Max Merchant Funding', 'Max Merchant Funding', 'debanked', true, 'token'),
  ('Max Advance', 'Max Advance', 'debanked', true, 'token'),
  ('Kings Cash Group', 'Kings Cash Group', 'debanked', true, 'token'),
  ('Kings Cash Group, LLC', 'Kings Cash Group', 'debanked', true, 'token'),
  ('Happy Rock Merchant Solutions', 'Happy Rock Merchant Solutions', 'debanked', true, 'token'),
  ('Gibraltar Capital Advance', 'Gibraltar Capital Advance', 'debanked', true, 'token'),
  ('Express Working Capital', 'Express Working Capital', 'debanked', true, 'token'),
  ('DB Squared', 'DB Squared', 'debanked', true, 'token'),
  ('DB Squared Inc', 'DB Squared', 'debanked', true, 'token'),
  ('Corona Advances', 'Corona Advances', 'debanked', true, 'token'),
  ('Commonwealth Merchant Advance', 'Commonwealth Merchant Advance', 'debanked', true, 'token'),
  ('Commonwealth Merchant Advance, Inc.', 'Commonwealth Merchant Advance', 'debanked', true, 'token'),
  ('Cash Cow Capital', 'Cash Cow Capital', 'debanked', true, 'token'),
  ('Cash Cow Capital LLC', 'Cash Cow Capital', 'debanked', true, 'token'),
  ('CapCall', 'CapCall', 'debanked', true, 'token'),
  ('CapCall LLC', 'CapCall', 'debanked', true, 'token'),
  ('Business Consulting Options', 'Business Consulting Options', 'debanked', true, 'token'),
  ('Bushwick Merchant Services', 'Bushwick Merchant Services', 'debanked', true, 'token'),
  ('American Allied Funding', 'American Allied Funding', 'debanked', true, 'token'),
  ('1st Merchant Funding', '1st Merchant Funding', 'debanked', true, 'token'),
  ('World Global Financing', 'World Global Financing', 'debanked', true, 'token'),
  ('The Smarter Merchant', 'The Smarter Merchant', 'debanked', true, 'token'),
  ('BizFund', 'BizFund', 'debanked', true, 'token'),
  ('Bizfund LLC', 'BizFund', 'debanked', true, 'token'),
  ('Meged Funding', 'Meged Funding', 'debanked', true, 'token'),
  ('Meged Funding Group LLC', 'Meged Funding', 'debanked', true, 'token'),
  ('Delancey Street Lending', 'Delancey Street Lending', 'debanked', true, 'token'),
  ('Delancey Street Lending Inc', 'Delancey Street Lending', 'debanked', true, 'token'),
  ('Delancey Street', 'Delancey Street Lending', 'debanked', true, 'token'),
  ('Nexi Finance (fka Fundamental Capital)', 'Nexi Finance (fka Fundamental Capital)', 'debanked', true, 'token'),
  ('Quikstone Capital', 'Quikstone Capital', 'debanked', true, 'token'),
  ('Quikstone Capital Solutions', 'Quikstone Capital', 'debanked', true, 'token'),
  ('Advantage Merchant Funding', 'Advantage Merchant Funding', 'debanked', true, 'token'),
  ('Alfa Advance Funding', 'Alfa Advance Funding', 'debanked', true, 'token'),
  ('Altbanq', 'Altbanq', 'debanked', true, 'token'),
  ('Alva Advance', 'Alva Advance', 'debanked', true, 'token'),
  ('Aquina Health', 'Aquina Health', 'debanked', true, 'token'),
  ('Arcarius', 'Arcarius', 'debanked', true, 'token'),
  ('Arcarius Funding', 'Arcarius', 'debanked', true, 'token'),
  ('Backd Business Funding', 'Backd Business Funding', 'debanked', true, 'token'),
  ('Backd', 'Backd Business Funding', 'debanked', true, 'token'),
  ('GetBackd', 'Backd Business Funding', 'debanked', true, 'token'),
  ('BIG (Blackbridge Investment Group)', 'BIG (Blackbridge Investment Group)', 'debanked', true, 'token'),
  ('Birkin Capital', 'Birkin Capital', 'debanked', true, 'token'),
  ('Bluebridge Funding', 'Bluebridge Funding', 'debanked', true, 'token'),
  ('Boom Funded', 'Boom Funded', 'debanked', true, 'token'),
  ('Bow Apple Capital', 'Bow Apple Capital', 'debanked', true, 'token'),
  ('Business Capital Providers', 'Business Capital Providers', 'debanked', true, 'token'),
  ('Cap Fund Now', 'Cap Fund Now', 'debanked', true, 'token'),
  ('Capback', 'Capback', 'debanked', true, 'token'),
  ('Capitalize Group', 'Capitalize Group', 'debanked', true, 'token'),
  ('Capytal', 'Capytal', 'debanked', true, 'token'),
  ('Cashium Capital', 'Cashium Capital', 'debanked', true, 'token'),
  ('Central Diligence Group', 'Central Diligence Group', 'debanked', true, 'token'),
  ('Clarity Advance', 'Clarity Advance', 'debanked', true, 'token'),
  ('Clearfund Solutions', 'Clearfund Solutions', 'debanked', true, 'token'),
  ('Family Business Fund', 'Family Business Fund', 'debanked', true, 'token'),
  ('Finova Capital', 'Finova Capital', 'debanked', true, 'token'),
  ('Fintap', 'Fintap', 'debanked', true, 'token'),
  ('Fintech Capital Group', 'Fintech Capital Group', 'debanked', true, 'token'),
  ('Fintegra', 'Fintegra', 'debanked', true, 'token'),
  ('Forward Line', 'Forward Line', 'debanked', true, 'token'),
  ('Fundpro', 'Fundpro', 'debanked', true, 'token'),
  ('Fundpro LLC', 'Fundpro', 'debanked', true, 'token'),
  ('Fundr', 'Fundr', 'debanked', true, 'token'),
  ('Fundura Capital', 'Fundura Capital', 'debanked', true, 'token'),
  ('Fundura Capital Group', 'Fundura Capital', 'debanked', true, 'token'),
  ('Fundx', 'Fundx', 'debanked', true, 'token'),
  ('G&G Funding Group', 'G and G Funding', 'debanked', true, 'token'),
  ('Global Funding Networks', 'GFE', 'debanked', true, 'token'),
  ('Granite Merchant Funding', 'Granite Merchant Funding', 'debanked', true, 'token'),
  ('Green Buck Capital', 'Green Buck Capital', 'debanked', true, 'token'),
  ('Hunter Caroline', 'Hunter Caroline', 'debanked', true, 'token'),
  ('Hunter Caroline Business Solutions', 'Hunter Caroline', 'debanked', true, 'token'),
  ('Instafund Advance', 'Instafund Advance', 'debanked', true, 'token'),
  ('Lendbug', 'Lendbug', 'debanked', true, 'token'),
  ('Lendfi', 'Lendfi', 'debanked', true, 'token'),
  ('Lendfi Corp', 'Lendfi', 'debanked', true, 'token'),
  ('Lexio Capital', 'Lexio Capital', 'debanked', true, 'token'),
  ('Main Street Cash', 'Main Street Cash', 'debanked', true, 'token'),
  ('Merit Business Funding', 'Merit Business Funding', 'debanked', true, 'token'),
  ('Monera Capital Group', 'Monera Capital Group', 'debanked', true, 'token'),
  ('Novus Capital Funding II', 'Novus Capital Funding', 'debanked', true, 'token'),
  ('Nulook Capital', 'Nulook Capital', 'debanked', true, 'token'),
  ('Octane Financing', 'Octane Financing', 'debanked', true, 'token'),
  ('Ontap Capital', 'Ontap Capital', 'debanked', true, 'token'),
  ('River Advance', 'River Advance', 'debanked', true, 'token'),
  ('Riverstrong Capital', 'Riverstrong Capital', 'debanked', true, 'token'),
  ('Secure Funding Source', 'Secure Funding Source', 'debanked', true, 'token'),
  ('Silver Street Funding', 'Silver Street Funding', 'debanked', true, 'token'),
  ('SPG Advance', 'SPG Advance', 'debanked', true, 'token'),
  ('SRS Capital Funds', 'SRS Capital Funds', 'debanked', true, 'token'),
  ('SRS Capital Funds Inc', 'SRS Capital Funds', 'debanked', true, 'token'),
  ('Super Fast Cap', 'Super Fast Cap', 'debanked', true, 'token'),
  ('Swift Funding Source', 'Swift Funding Source', 'debanked', true, 'token'),
  ('Union Funding Source', 'Union Funding Source', 'debanked', true, 'token'),
  ('Upsize Capital', 'Upsize Capital', 'debanked', true, 'token'),
  ('Vader Mountain Capital', 'Vader Mountain Capital', 'debanked', true, 'token'),
  ('Vital Cap Fund', 'Vital Cap Fund', 'debanked', true, 'token'),
  ('Vital Cap', 'Vital Cap Fund', 'debanked', true, 'token'),
  ('Wefund', 'Wefund', 'debanked', true, 'token'),
  ('Efinancial Tree', 'Efinancial Tree', 'debanked', true, 'token'),
  ('In Advance Capital', 'In Advance Capital', 'debanked', true, 'token'),
  ('LoopOne Funding', 'LoopOne Funding', 'debanked', true, 'token'),
  ('South End Capital', 'South End Capital', 'debanked', true, 'token'),
  ('South End Capital Corporation', 'South End Capital', 'debanked', true, 'token'),
  ('TMR Now', 'Total Merchant Resources', 'debanked', true, 'token'),
  ('World Business Lenders', 'World Business Lenders', 'debanked', true, 'token'),
  ('World Business Lenders, LLC', 'World Business Lenders', 'debanked', true, 'token'),
  ('Grantly Funding', 'Grantly Funding', 'debanked', true, 'token'),
  ('Big Think Capital', 'Big Think Capital', 'debanked', true, 'token'),
  ('Global Funding Experts', 'United First', 'debanked', true, 'token'),
  ('UF Capital Experts', 'United First', 'debanked', true, 'token'),
  ('GTR Source', 'GTR Source', 'debanked', true, 'token'),
  ('GTR Source, LLC', 'GTR Source', 'debanked', true, 'token'),
  ('Cardinal Equity', 'Cardinal Equity', 'debanked', true, 'token'),
  ('Cardinal Equity Partners', 'Cardinal Equity', 'debanked', true, 'token'),
  ('BMF Advance LLC', 'BMF Capital', 'debanked', true, 'token'),
  ('Quarterspot', 'Quarterspot', 'debanked', true, 'token'),
  ('QuarterSpot, Inc.', 'Quarterspot', 'debanked', true, 'token'),
  ('Payability', 'Payability', 'debanked', true, 'token'),
  ('Wewire', 'EIN Cap', 'debanked', true, 'token'),
  ('Hi-Bar Capital', 'EIN Cap', 'debanked', true, 'token'),
  ('Hi Bar Capital', 'Hi Bar Capital', 'debanked', true, 'token'),
  ('Hi-Bar Capital LLC', 'Hi Bar Capital', 'debanked', true, 'token'),
  ('Karish Capital', 'Karish Capital', 'debanked', true, 'token'),
  ('Karish Kapital', 'Karish Capital', 'debanked', true, 'token'),
  ('Kingdom Kapital', 'Kingdom Kapital', 'debanked', true, 'token'),
  ('Legacy Capital 26 LLC', 'Legacy Capital', 'debanked', true, 'token'),
  ('MFS Global', 'MFS Global', 'debanked', true, 'token'),
  ('One Park Financial', 'One Park Financial', 'debanked', true, 'token'),
  ('Peak Solutions', 'Peak Solutions', 'debanked', true, 'token'),
  ('Pledge Cap', 'Pledge Cap', 'debanked', true, 'token'),
  ('Second Chance Funding', 'Second Chance Funding', 'debanked', true, 'token'),
  ('Silver Cup Funding', 'Silver Cup Funding', 'debanked', true, 'token'),
  ('Streamline Consultants', 'Streamline Consultants', 'debanked', true, 'token'),
  ('24 Hour Capital', '24 Hour Capital', 'debanked', true, 'token'),
  ('24/7 Capital', '24/7 Capital', 'debanked', true, 'token'),
  ('60 Day Capital', '60 Day Capital', 'debanked', true, 'token'),
  ('1st Global Systems', '1st Global Systems', 'debanked', true, 'token'),
  ('Austin Business Finance', 'Austin Business Finance', 'debanked', true, 'token'),
  ('Austin Business Finance LLC', 'Austin Business Finance', 'debanked', true, 'token'),
  ('Banana Exchange', 'Banana Exchange', 'debanked', true, 'token'),
  ('Cambridge Funding Source', 'Cambridge Funding Source', 'debanked', true, 'token'),
  ('Eagle Eye Advance', 'Eagle Eye Advance', 'debanked', true, 'token'),
  ('Five Tower', 'Five Tower', 'debanked', true, 'token'),
  ('Five Tower Capital', 'Five Tower', 'debanked', true, 'token'),
  ('Funderz.net', 'Funderz.net', 'debanked', true, 'token'),
  ('Funderz.net LLC', 'Funderz.net', 'debanked', true, 'token'),
  ('Fundz.net', 'Funderz.net', 'debanked', true, 'token'),
  ('Loan Me', 'Loan Me', 'debanked', true, 'token'),
  ('LoanMe, Inc.', 'Loan Me', 'debanked', true, 'token'),
  ('Main Street Funders', 'Main Street Funders', 'debanked', true, 'token'),
  ('ML Factors', 'ML Factors', 'debanked', true, 'token'),
  ('ML Factors Funding', 'ML Factors', 'debanked', true, 'token'),
  ('New Logic Business Loans', 'New Logic Business Loans', 'debanked', true, 'token'),
  ('New Logic', 'New Logic Business Loans', 'debanked', true, 'token'),
  ('NRO Boston', 'NRO Boston', 'debanked', true, 'token'),
  ('Same Day Financing', 'Same Day Financing', 'debanked', true, 'token'),
  ('Bizfi', 'Bizfi', 'debanked', true, 'token'),
  ('Bizfi, LLC', 'Bizfi', 'debanked', true, 'token'),
  ('Nexi (Business Backer parent Enova)', 'Nexi (Business Backer parent Enova)', 'debanked', true, 'token'),
  ('CashReady', 'CashReady', 'debanked', true, 'token'),
  ('CashReady, LLC', 'CashReady', 'debanked', true, 'token'),
  ('Cash On Demand', 'Cash On Demand', 'debanked', true, 'token'),
  ('Cash-On-Demand', 'Cash On Demand', 'debanked', true, 'token'),
  ('Dealstruck', 'Dealstruck', 'debanked', true, 'token'),
  ('Mybusinessloan.com LLC', 'Dealstruck', 'debanked', true, 'token'),
  ('Ifunds Cash Solutions', 'Ifunds Cash Solutions', 'debanked', true, 'token'),
  ('Infinicap', 'Infinicap', 'debanked', true, 'token'),
  ('Merit Capital Advance', 'Merit Capital Advance', 'debanked', true, 'token'),
  ('Royal Advance', 'Royal Advance', 'debanked', true, 'token')
on conflict (alias) do update set
  canonical_name = excluded.canonical_name, source = excluded.source,
  active = true, match_mode = excluded.match_mode;

-- ── EXACT-mode aliases (101) ──────────────────────────────────────────
insert into public.ph_ucc_funder_aliases (alias, canonical_name, source, active, match_mode) values
  ('Fox Capital Group', 'Fox Business Funding', 'debanked', true, 'exact'),
  ('Fox Capital Group, Inc.', 'Fox Business Funding', 'debanked', true, 'exact'),
  ('Merchant Capital Group LLC', 'Greenbox Capital', 'debanked', true, 'exact'),
  ('ARF Financial', 'ARF Financial', 'debanked', true, 'exact'),
  ('Partners Funding', 'Bankcard Funding', 'debanked', true, 'exact'),
  ('Infusion Capital Group', 'Infusion Capital Group', 'debanked', true, 'exact'),
  ('Infusion Capital Group LLC', 'Infusion Capital Group', 'debanked', true, 'exact'),
  ('Superior Capital', 'Superior Capital', 'debanked', true, 'exact'),
  ('Garden Funding', 'Garden Funding', 'debanked', true, 'exact'),
  ('Good Funding', 'Good Funding', 'debanked', true, 'exact'),
  ('JRG Funding', 'JRG Funding', 'debanked', true, 'exact'),
  ('SDY Capital', 'SDY Capital', 'debanked', true, 'exact'),
  ('Select Funding', 'Select Funding', 'debanked', true, 'exact'),
  ('Zlur Funding', 'Zlur Funding', 'debanked', true, 'exact'),
  ('PDM Capital', 'PDM Capital', 'debanked', true, 'exact'),
  ('PDM Capital LLC', 'PDM Capital', 'debanked', true, 'exact'),
  ('Fast Capital', 'Fast Capital', 'debanked', true, 'exact'),
  ('Capital Advance Services LLC', 'Yellowstone Capital', 'debanked', true, 'exact'),
  ('Capital Merchant Services LLC', 'Yellowstone Capital', 'debanked', true, 'exact'),
  ('Merchant Funding Services LLC', 'Yellowstone Capital', 'debanked', true, 'exact'),
  ('WCM Funding LLC', 'Yellowstone Capital', 'debanked', true, 'exact'),
  ('YES Funding', 'Yellowstone Capital', 'debanked', true, 'exact'),
  ('Richmond Capital Group', 'Richmond Capital Group', 'debanked', true, 'exact'),
  ('Viceroy Capital Funding', 'Richmond Capital Group', 'debanked', true, 'exact'),
  ('Ram Capital Funding', 'Richmond Capital Group', 'debanked', true, 'exact'),
  ('RAM Capital Funding, LLC', 'Ram Capital Funding', 'debanked', true, 'exact'),
  ('Retail Capital, LLC', 'Credibly', 'debanked', true, 'exact'),
  ('Capital Options LLC', 'CAN Capital', 'debanked', true, 'exact'),
  ('Pearl Capital', 'Pearl Capital', 'debanked', true, 'exact'),
  ('Par Funding', 'Par Funding', 'debanked', true, 'exact'),
  ('Wall Funding', 'Wall Funding', 'debanked', true, 'exact'),
  ('VWM Group, LLC', 'ARF Financial', 'debanked', true, 'exact'),
  ('Mother Funding', 'Mother Funding', 'debanked', true, 'exact'),
  ('H Capital', 'Yalber', 'debanked', true, 'exact'),
  ('Sterling Funding', 'Sterling Funding', 'debanked', true, 'exact'),
  ('BC Funding, LLC', 'Bankcard Funding', 'debanked', true, 'exact'),
  ('Knight Capital Funding', 'Knight Capital Funding', 'debanked', true, 'exact'),
  ('TVT Capital LLC', 'Yellowstone-linked TVT Capital', 'debanked', true, 'exact'),
  ('Arsenal Funding', 'Prosperum Capital', 'debanked', true, 'exact'),
  ('Jumpstart Capital', 'Jumpstart Capital', 'debanked', true, 'exact'),
  ('Jumpstart Capital LLC', 'Jumpstart Capital', 'debanked', true, 'exact'),
  ('Grand Capital Funding', 'Grand Capital Funding', 'debanked', true, 'exact'),
  ('Grand Capital Funding LLC', 'Grand Capital Funding', 'debanked', true, 'exact'),
  ('Parkside Funding Group', 'Parkside Funding Group', 'debanked', true, 'exact'),
  ('Parkside Funding Group LLC', 'Parkside Funding Group', 'debanked', true, 'exact'),
  ('Arch Capital Funding', 'Arch Capital Funding', 'debanked', true, 'exact'),
  ('Arch Capital Funding, LLC', 'Arch Capital Funding', 'debanked', true, 'exact'),
  ('LG Funding', 'LG Funding', 'debanked', true, 'exact'),
  ('LG Funding, LLC', 'LG Funding', 'debanked', true, 'exact'),
  ('Merk Funding', 'Merk Funding', 'debanked', true, 'exact'),
  ('Merk Funding Inc.', 'Merk Funding', 'debanked', true, 'exact'),
  ('Smart Choice Capital', 'Smart Choice Capital', 'debanked', true, 'exact'),
  ('Kash Capital', 'Kash Capital', 'debanked', true, 'exact'),
  ('Hop Capital', 'Hop Capital', 'debanked', true, 'exact'),
  ('GRP Funding', 'GRP Funding', 'debanked', true, 'exact'),
  ('Experience Finance', 'Experience Finance', 'debanked', true, 'exact'),
  ('Centerboard Funding', 'Centerboard Funding', 'debanked', true, 'exact'),
  ('American Finance Solutions', 'American Finance Solutions', 'debanked', true, 'exact'),
  ('Velocity Capital Group', 'Velocity Capital Group', 'debanked', true, 'exact'),
  ('Velocity Capital Group LLC', 'Velocity Capital Group', 'debanked', true, 'exact'),
  ('Nexi Finance', 'Nexi Finance (fka Fundamental Capital)', 'debanked', true, 'exact'),
  ('Fundamental Capital, LLC', 'Nexi Finance (fka Fundamental Capital)', 'debanked', true, 'exact'),
  ('Aspire Funding', 'Aspire Funding', 'debanked', true, 'exact'),
  ('Belltower Funding', 'Belltower Funding', 'debanked', true, 'exact'),
  ('Blade Funding', 'Blade Funding', 'debanked', true, 'exact'),
  ('Bridge Funding Capital', 'Bridge Funding Capital', 'debanked', true, 'exact'),
  ('Cityview Funding', 'Cityview Funding', 'debanked', true, 'exact'),
  ('Eminent Funding', 'Eminent Funding', 'debanked', true, 'exact'),
  ('Essential Funding', 'Essential Funding', 'debanked', true, 'exact'),
  ('Fresh Funding', 'Fresh Funding', 'debanked', true, 'exact'),
  ('Fund 4 Less', 'Fund 4 Less', 'debanked', true, 'exact'),
  ('Fusion Funding', 'Fusion Funding', 'debanked', true, 'exact'),
  ('Jett Capital', 'Jett Capital', 'debanked', true, 'exact'),
  ('Jet Capital', 'Jett Capital', 'debanked', true, 'exact'),
  ('Masada Funding', 'Masada Funding', 'debanked', true, 'exact'),
  ('Mint Funding', 'Mint Funding', 'debanked', true, 'exact'),
  ('Novo Funding', 'Novo Funding', 'debanked', true, 'exact'),
  ('Novus Capital Funding', 'Novus Capital Funding', 'debanked', true, 'exact'),
  ('Onnx Funding', 'Onnx Funding', 'debanked', true, 'exact'),
  ('Quicksilver Capital', 'Quicksilver Capital', 'debanked', true, 'exact'),
  ('RBS Funding', 'RBS Funding', 'debanked', true, 'exact'),
  ('Reliable Funding', 'Reliable Funding', 'debanked', true, 'exact'),
  ('Reliance Financial', 'Reliance Financial', 'debanked', true, 'exact'),
  ('SBL Funding', 'SBL Funding', 'debanked', true, 'exact'),
  ('Simply Funding', 'Simply Funding', 'debanked', true, 'exact'),
  ('Strategic Capital', 'Strategic Capital', 'debanked', true, 'exact'),
  ('Sutton Funding', 'Sutton Funding', 'debanked', true, 'exact'),
  ('Thor Capital Group', 'Thor Capital Group', 'debanked', true, 'exact'),
  ('Uptown Fund', 'Uptown Fund', 'debanked', true, 'exact'),
  ('Waterview Capital', 'Waterview Capital', 'debanked', true, 'exact'),
  ('BHB Funding', 'BHB Funding', 'debanked', true, 'exact'),
  ('MNR Capital Group', 'MNR Capital Group', 'debanked', true, 'exact'),
  ('Spin Capital', 'Spin Capital', 'debanked', true, 'exact'),
  ('Spin Capital LLC', 'Spin Capital', 'debanked', true, 'exact'),
  ('BMF Capital', 'BMF Capital', 'debanked', true, 'exact'),
  ('Queen Funding', 'Queen Funding', 'debanked', true, 'exact'),
  ('Queen Funding LLC', 'Queen Funding', 'debanked', true, 'exact'),
  ('Propulsion Funding', 'Propulsion Funding', 'debanked', true, 'exact'),
  ('Acacia Funding', 'Acacia Funding', 'debanked', true, 'exact'),
  ('Windset Capital', 'Windset Capital', 'debanked', true, 'exact'),
  ('Windset Capital Corporation', 'Windset Capital', 'debanked', true, 'exact')
on conflict (alias) do update set
  canonical_name = excluded.canonical_name, source = excluded.source,
  active = true, match_mode = excluded.match_mode;
